//
// Created by Maria Baburina on 2018-07-26.
//

#ifndef VCSCHECKOUTTESTNOIDEAFILESCMAKELISTS_SOURCE_H
#define VCSCHECKOUTTESTNOIDEAFILESCMAKELISTS_SOURCE_H


class source {

};


#endif //VCSCHECKOUTTESTNOIDEAFILESCMAKELISTS_SOURCE_H
